name: ml_model_4
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - altair=6.0.0
  - aom=3.12.1
  - arrow-cpp=21.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - backports.zstd=1.2.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cachetools=6.2.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.2.1
  - contourpy=1.3.1
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - eigen=5.0.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.16
  - ftfy=6.3.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jansson=2.14
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - kernel-headers_linux-64=4.18.0
  - kiwisolver=1.4.9
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcups=2.4.15
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.67.1
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mesalib=25.1.5
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - narwhals=2.7.0
  - ncurses=6.5
  - networkx=3.4.2
  - numexpr=2.11.0
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - openblas=0.3.30
  - opencl-headers=2025.07.22
  - opencv=4.12.0
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - protobuf=5.29.3
  - pthread-stubs=0.3
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - regex=2025.11.3
  - requests=2.32.5
  - rpds-py=0.28.0
  - s2n=1.5.14
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - streamlit=1.52.2
  - sympy=1.14.0
  - sysroot_linux-64=2.28
  - tbb=2021.13.0
  - tenacity=9.1.2
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.2.1
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.2
  - utf8proc=2.6.1
  - watchdog=6.0.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - clip==1.0
      - pyarrow==22.0.0
prefix: /home/vu-nam-khanh/miniconda3/envs/ml_model_4
